# Generated by Django 4.2.5 on 2023-09-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='File'),
        ),
    ]
