# Generated by Django 4.2.5 on 2023-09-23 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0005_file_user_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_user_permission',
            new_name='FileUserPermission',
        ),
    ]
